#!/usr/bin/env python3
"""Write mkdocs.yml, deriving the nav from tools/manifest.py.

Keeping the nav in one place stops the config and the converter from drifting
apart when pages are added or moved.
"""
import os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from manifest import NAV

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEADER = '''# Generated by tools/gen_mkdocs.py — edit that script, not this file.
site_name: Moto Mods Developer Documentation
site_description: >-
  A restored archive of the Moto Mods developer documentation originally
  published at developer.motorola.com, rebuilt from Wayback Machine captures.
site_url: https://jksim.github.io/MotoMods-Developer-Docs/
repo_url: https://github.com/jksim/MotoMods-Developer-Docs
repo_name: MotoMods-Developer-Docs
edit_uri: ""
copyright: >-
  Original documentation &copy; Motorola Mobility LLC. Archived for historical
  and educational reference; not affiliated with or endorsed by Motorola or Lenovo.

docs_dir: docs
site_dir: site

theme:
  name: material
  language: en
  icon:
    logo: material/cellphone-link
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.tooltips
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Follow system theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  # Renders the :material-*: icon shortcodes used on the home page cards.
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jksim/MotoMods-Developer-Docs
      name: This archive on GitHub

nav:
'''


def emit(items, indent):
    pad = '  ' * indent
    out = []
    for title, target in items:
        if isinstance(target, list):
            out.append(f'{pad}- {title}:')
            out.extend(emit(target, indent + 1))
        else:
            out.append(f'{pad}- {title}: {target}')
    return out


def main():
    lines = emit(NAV, 1)
    missing = [t for t in flatten(NAV)
               if not os.path.isfile(os.path.join(ROOT, 'docs', t))]
    for m in missing:
        print(f'WARN nav points at a page that does not exist: {m}')
    with open(os.path.join(ROOT, 'mkdocs.yml'), 'w') as fh:
        fh.write(HEADER + '\n'.join(lines) + '\n')
    print(f'wrote mkdocs.yml with {len(lines)} nav entries')


def flatten(items):
    for _, target in items:
        if isinstance(target, list):
            yield from flatten(target)
        else:
            yield target


if __name__ == '__main__':
    main()
